#!/bin/bash

if [ -z "$1" ]; then
    read -sp "Please enter your GitHub Personal Access Token: " GITHUB_PAT
    echo
else
    GITHUB_PAT=$1
fi

if [ -z "$GITHUB_PAT" ]; then
    echo "GitHub Personal Access Token is required"
    exit 1
fi

# Install depedencies
sudo apt install build-essential curl python3-pip python3.12-venv
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
source ~/.bashrc
nvm install 22
node -v
npm -v

# Clone repositories
git clone https://${GITHUB_PAT}@github.com/rix-ros/rix-util
git clone https://${GITHUB_PAT}@github.com/rix-ros/rix-msg
git clone https://${GITHUB_PAT}@github.com/rix-ros/rix-ipc
git clone https://${GITHUB_PAT}@github.com/rix-ros/rix-core
git clone https://${GITHUB_PAT}@github.com/rix-ros/rix-py
git clone https://${GITHUB_PAT}@github.com/rix-ros/rix-js

cd rix-util
chmod +x install.sh
./install.sh

cd ../rix-msg
python3 -m venv venv
source venv/bin/activate
pip install pyinstaller
chmod +x install.sh
./install.sh
deactivate

cd ../rix-ipc
chmod +x install.sh
./install.sh

cd ../rix-core
chmod +x install.sh
./install.sh

cd ../rix-py
chmod +x install.sh
./install.sh

cd ../rix-js
chmod +x install.sh
./install.sh

cd ..
rm -rf rix-util rix-msg rix-ipc rix-core rix-py rix-js

echo "Installation complete"
